import { Router, Request, Response, NextFunction } from 'express';
import PDFDocument from 'pdfkit';
import { Inspection } from '../../models/Inspection';
import { createError } from '../middleware/error-handler';

const router = Router();

// GET /api/v1/reports/:inspectionId/pdf
router.get('/:inspectionId/pdf', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const inspection = await Inspection.findOne({
      inspectionId: req.params.inspectionId,
    }).populate('inspector', 'name email').lean();

    if (!inspection) throw createError('Inspection not found', 404, 'NOT_FOUND');

    // Generate PDF
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader(
      'Content-Disposition',
      `attachment; filename="aed-inspection-${inspection.inspectionId}.pdf"`,
    );
    doc.pipe(res);

    // ── Header ──────────────────────────────────────────────────
    doc.fontSize(20).font('Helvetica-Bold').text('AED Inspection Report', { align: 'center' });
    doc.moveDown(0.5);

    const resultColor =
      inspection.inspectionResult === 'PASS'
        ? '#16a34a'
        : inspection.inspectionResult === 'FAIL'
          ? '#dc2626'
          : '#d97706';

    doc
      .fontSize(14)
      .fillColor(resultColor)
      .font('Helvetica-Bold')
      .text(`Result: ${inspection.inspectionResult}`, { align: 'center' });

    doc.fillColor('#000000').moveDown();

    // ── Divider ──────────────────────────────────────────────────
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke().moveDown(0.5);

    // ── Details table ────────────────────────────────────────────
    const rows: [string, string][] = [
      ['Inspection ID', inspection.inspectionId],
      ['Date', inspection.startedAt ? new Date(inspection.startedAt).toLocaleString() : 'N/A'],
      [
        'Inspector',
        // @ts-ignore — populated
        inspection.inspector?.name ?? 'Unknown',
      ],
      ['Manufacturer', inspection.manufacturer ?? 'Not detected'],
      ['Model', inspection.aedModel ?? 'Not detected'],
      ['Serial Number', inspection.serialNumber ?? 'Not captured'],
      ['Pads Expiry', inspection.padsExpiry ?? 'Not captured'],
      ['Battery Expiry', inspection.batteryExpiry ?? 'Not captured'],
      ['Status Indicator', inspection.statusIndicator ?? 'Not checked'],
      [
        'Status Confidence',
        inspection.statusConfidence ? `${Math.round(inspection.statusConfidence * 100)}%` : 'N/A',
      ],
      [
        'Duration',
        inspection.durationSeconds ? `${Math.round(inspection.durationSeconds)}s` : 'N/A',
      ],
      ['Location', inspection.locationId ?? 'Not specified'],
      ['Notes', inspection.notes ?? '—'],
    ];

    doc.font('Helvetica').fontSize(10);
    for (const [label, value] of rows) {
      doc.font('Helvetica-Bold').text(label + ': ', { continued: true }).font('Helvetica').text(value);
    }

    doc.moveDown();
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke().moveDown(0.5);

    // ── Footer ───────────────────────────────────────────────────
    doc.fontSize(8).fillColor('#666').text(
      `Generated by AED Inspection Platform • ${new Date().toISOString()}`,
      { align: 'center' },
    );

    doc.end();
  } catch (err) {
    next(err);
  }
});

// GET /api/v1/reports/:inspectionId/json
router.get('/:inspectionId/json', async (req: Request, res: Response, next: NextFunction) => {
  try {
    const inspection = await Inspection.findOne({ inspectionId: req.params.inspectionId })
      .populate('inspector', 'name email')
      .lean();
    if (!inspection) throw createError('Inspection not found', 404, 'NOT_FOUND');
    res.json({ report: inspection });
  } catch (err) {
    next(err);
  }
});

export default router;
